# PATHS
train_dataset: ./data/train
validation_dataset: ./data/eval
#predict_dataset: ./data/predict
#load_model_path: ./CheckPoint/<checkpoint_file>
additional_functions_file: ./additional_functions.py
output_path: ./

# OPTIMIZATION OPTIONS
loss: MeanSquaredError
optimizer:
  type: Adam
metrics: [MeanAbsoluteError]

# TRAINING OPTIONS
batch_size: 16
epochs: 100
epoch_size: 3000
shuffle_training_set: True
shuffle_validation_set: False
val_samples: 1000
val_frequency: 1